### ISSUE TITLE
How to make `Jest` + `esbuild-plugin-glsl` work

### ISSUE THREAD

**Issue by josemac95** [vanruesc/esbuild-plugin-glsl#6] opened 2023-03-31 11:20 UTC
First of all, great plugin!

I've been trying to set up `esbuild-plugin-glsl` with `Jest` but my tests were failing despite the code working fine:

```
● Test suite failed to run

  Jest encountered an unexpected token

  Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

  Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

  By default "node_modules" folder is ignored by transformers.

  Here's what you can do:
   • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
   • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
   • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
   • If you need a custom transformation specify a "transform" option in your config.
   • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

  You'll find more details and examples of these config options in the docs:
  https://jestjs.io/docs/configuration
  For information about custom transformations, see:
  https://jestjs.io/docs/code-transformation

  Details:

  /shader.vert:1
  ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){varying vec2 vUv;
                                                                                            ^^^^

  SyntaxError: Unexpected identifier
```

Here's a workaround I came up with in case anyone stumbles upon the same problem:

1. ➕  Add [jest-transform-stub](https://github.com/eddyerburgh/jest-transform-stub) to avoid errors when importing non JavaScript assets.
2. 🔧 Add this configuration to the `Jest` section of your `package.json` file:
	```
	"moduleNameMapper": {
	  "^.+.(vert|frag|glsl)$": "jest-transform-stub"
	}
	```

**Comment by vanruesc** [comment] 2023-03-31 11:40
This plugin integrates shader code imports as string constants during the esbuild build process.

I'm assuming your unit tests import from your sources instead of the final bundle which means that the custom shader imports are still present and can't be resolved by Jest. If that's the case, I'd recommend importing from your bundle instead.

I'm not familiar with Jest, but with Ava.js, for example, you can `import xyz from "my-package"` and it imports from the exports specified in your `package.json`.

**Comment by markets** [comment] 2023-03-31 12:46
Hi @vanruesc and thanks for your quick response! 

Yes, importing the final bundle will make it work in tests too without the need of extra stuff (as you do using Ava.js), but the problem is that our app is quite big and we are implementing unit-tests using ESM directly from sources (no build process involved). Our current approach with the `jest-transform-stub` works just fine and we just wanted to share it in case it helps eventual future readers. But yeah, probably having a build process (which will resolve shaders files) before starting tests is a good idea too! We'll try thanks!

**Closed** 2023-03-31 21:28 UTC
